sonar.projectKey=Fiscaliza
sonar.sources=.

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.maven.coverage.reportPaths=coverage.xml

sonar.exclusions=
