spring.application.name=fiscaliza

spring.security.user.name=admin
spring.security.user.password=123456

spring.datasource.url=jdbc:h2:file:./data/fiscaliza
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
