spring.application.name=fiscaliza

spring.security.user.name=admin
spring.security.user.password=123456

spring.datasource.url=jdbc:h2:file:./data/fiscaliza
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Desativa a criação automática do Hibernate (o Flyway vai cuidar do banco)
spring.jpa.hibernate.ddl-auto=validate

# Ativa o Flyway
spring.flyway.enabled=true

spring.h2.console.enabled=true
